logo = "display/screens/logo"
not_found = "display/screens/notfound"
application = "display/screens/applic"
welcome = "display/screens/welcome"
new_user1 = "display/screens/newuser1"
new_user2 = "display/screens/newuser2"
rookie = "display/screens/welcome"
not_configured = ""
quote = "display/screens/quotes"
day_limit = "display/screens/daylimit"
time_warn = "display/screens/timewarn"
too_slow = "display/screens/tooslow"
bye_bye = "display/screens/byebye"
bad_logon = "display/screens/badlogon"
barricade = "display/screens/barricad"
no_space = "display/screens/nospace"
no_mail = "display/screens/nomail"
area_not_exist = ""
chat_begin = ""
chat_end = ""
out_leaving = ""
out_return = ""
shell_to_dos = "display/screens/shellbye"
back_from_dos = "display/screens/shellhi"
locate = "display/help/locate"
contents = "display/help/contents"
oped_help = "display/help/fsed"
line_ed_help = "display/help/1stedit"
replace_help = "display/help/rep_edit"
inquire_help = ""
scan_help = ""
list_help = ""
header_help = "display/screens/hdrentry"
entry_help = "display/screens/msgentry"
xfer_baud = "display/screens/xferbaud"
file_area_list = ""
file_header = "%x16%x01%x0fFile Areas %x16%x01%x0d%xc4%xc4%xc4%xc4%xc4%xc4%xc4%xc4%xc4%xc4%xc4%xc4%xc4%xc4%x0a%x0a"
file_format = "|tx[|hd%-4t|tx]|pr %-20a |tx... %-n%x0a"
file_footer = "%x0a|prLocation: |hi%b|07%x0a"
msg_area_list = ""
msg_header = "%x16%x01%x0fMessage Areas %x16%x01%x0d%xc4%xc4%xc4%xc4%xc4%xc4%xc4%xc4%xc4%xc4%xc4%xc4%xc4%xc4%x0a%x0a"
msg_format = "%x16%x01%x0e%*%x16%x01%x0d%-20#%x16%x01%x07 ... %x16%x01%x03%n%x0a"
msg_footer = "%x0a|prLocation: |hi%b|07%x0a"
protocol_dump = ""
fname_format = "display/screens/fformat"
time_format = "%H:%M:%S"
date_format = "%C-%D-%Y"
tune = "display/tunes/tunes"
