alias_system = true
ask_alias = true
single_word_names = true
check_ansi = true
check_rip = true
ask_phone = true
no_real_name = false
disable_userlist = false
disable_magnet = false
edit_menu = ""
autodate = true
date_style = 0
filelist_margin = 0
exit_after_call = 5
chat_program = ""
local_editor = "/usr/bin/pico \"%s\""
yell_enabled = true
compat_local_baud_9600 = false
min_free_kb = 200
upload_log = "log/uploads.log"
virus_check = ""
mailchecker_reply_priv = 0
mailchecker_kill_priv = 0
comment_area = "1"
highest_message_area = "ZZZZZZZZZZ"
highest_file_area = "ZZZZZZZZZZ"
area_change_keys = "[]?"
chat_capture = false
strict_xfer = false
gate_netmail = false
global_high_bit = false
upload_check_dupe = true
upload_check_dupe_extension = false
use_umsgids = false
logon_priv = 20
logon_timelimit = 15
min_logon_baud = 0
min_graphics_baud = 1200
min_rip_baud = 65535
input_timeout = 15
max_msgsize = 8192
kill_private = "Never"
charset = ""
save_directories = []
track_privview = ""
track_privmod = ""
track_base = ""
track_exclude = ""
attach_base = "data/mail/attach"
attach_path = "data/mail/attach"
attach_archiver = "ZIP"
kill_attach = "ask"
msg_localattach_priv = 30
kill_attach_priv = 30
first_menu = "MAIN"
first_file_area = "1"
first_message_area = "Local Areas.1"
