[[access_level]]
name = "Transient"
level = 0
description = "Transient"
alias = "Twit"
key = "T"
time = 15
cume = 15
calls = -1
logon_baud = 300
xfer_baud = 300
file_limit = 0
file_ratio = 0
ratio_free = 250
upload_reward = 0
login_file = ""
flags = []
mail_flags = []
user_flags = 0
oldpriv = -2

[[access_level]]
name = "Demoted"
level = 10
description = "Demoted"
alias = "Disgrace"
key = "D"
time = 45
cume = 60
calls = -1
logon_baud = 300
xfer_baud = 300
file_limit = 500
file_ratio = 0
ratio_free = 500
upload_reward = 50
login_file = ""
flags = []
mail_flags = []
user_flags = 0
oldpriv = 0

[[access_level]]
name = "Limited"
level = 20
description = "Limited"
alias = ""
key = "L"
time = 60
cume = 90
calls = -1
logon_baud = 300
xfer_baud = 300
file_limit = 1000
file_ratio = 0
ratio_free = 1000
upload_reward = 100
login_file = ""
flags = []
mail_flags = []
user_flags = 0
oldpriv = 1

[[access_level]]
name = "Normal"
level = 30
description = "Normal"
alias = ""
key = "N"
time = 60
cume = 90
calls = -1
logon_baud = 300
xfer_baud = 300
file_limit = 5000
file_ratio = 0
ratio_free = 1000
upload_reward = 100
login_file = ""
flags = []
mail_flags = []
user_flags = 0
oldpriv = 2

[[access_level]]
name = "Worthy"
level = 40
description = "Worthy"
alias = ""
key = "W"
time = 60
cume = 90
calls = -1
logon_baud = 300
xfer_baud = 300
file_limit = 5000
file_ratio = 0
ratio_free = 1000
upload_reward = 100
login_file = ""
flags = []
mail_flags = []
user_flags = 0
oldpriv = 3

[[access_level]]
name = "Privil"
level = 50
description = "Privil"
alias = ""
key = "P"
time = 60
cume = 90
calls = -1
logon_baud = 300
xfer_baud = 300
file_limit = 5000
file_ratio = 0
ratio_free = 2000
upload_reward = 100
login_file = ""
flags = []
mail_flags = []
user_flags = 0
oldpriv = 4

[[access_level]]
name = "Favored"
level = 60
description = "Favored"
alias = ""
key = "F"
time = 60
cume = 90
calls = -1
logon_baud = 300
xfer_baud = 300
file_limit = 5000
file_ratio = 0
ratio_free = 5000
upload_reward = 100
login_file = ""
flags = []
mail_flags = []
user_flags = 0
oldpriv = 5

[[access_level]]
name = "Extra"
level = 70
description = "Extra"
alias = ""
key = "E"
time = 60
cume = 90
calls = -1
logon_baud = 300
xfer_baud = 300
file_limit = 5000
file_ratio = 0
ratio_free = 8000
upload_reward = 100
login_file = ""
flags = []
mail_flags = []
user_flags = 0
oldpriv = 6

[[access_level]]
name = "Clerk"
level = 80
description = "Clerk"
alias = ""
key = "C"
time = 90
cume = 120
calls = -1
logon_baud = 300
xfer_baud = 300
file_limit = 5000
file_ratio = 0
ratio_free = 10000
upload_reward = 100
login_file = ""
flags = []
mail_flags = []
user_flags = 0
oldpriv = 7

[[access_level]]
name = "AsstSysop"
level = 90
description = "AsstSysop"
alias = ""
key = "A"
time = 120
cume = 180
calls = -1
logon_baud = 300
xfer_baud = 300
file_limit = 5000
file_ratio = 0
ratio_free = 10000
upload_reward = 100
login_file = ""
flags = ["ShowHidden", "ShowAllFiles", "DloadHidden"]
mail_flags = ["LocalEditor", "NetFree", "WriteRdOnly"]
user_flags = 0
oldpriv = 8

[[access_level]]
name = "Sysop"
level = 100
description = "Sysop"
alias = ""
key = "S"
time = 1440
cume = 1440
calls = -1
logon_baud = 300
xfer_baud = 300
file_limit = 30000
file_ratio = 0
ratio_free = 10000
upload_reward = 100
login_file = ""
flags = ["ShowHidden", "ShowAllFiles", "DloadHidden", "UploadAny", "NoFileLimit"]
mail_flags = ["LocalEditor", "NetFree", "WriteRdOnly", "MsgAttrAny", "NoRealName"]
user_flags = 0
oldpriv = 10

[[access_level]]
name = "Hidden"
level = 65535
description = "Hidden"
alias = ""
key = "H"
time = 0
cume = 0
calls = 0
logon_baud = 300
xfer_baud = 1200
file_limit = 0
file_ratio = 0
ratio_free = 0
upload_reward = 0
login_file = ""
flags = ["HangUp", "Hide"]
mail_flags = []
user_flags = 0
oldpriv = 11
